### ISSUE TITLE
Charm doesn't react to pebble_ready so if the workload container restarts the charm stays in maintenance status

### ISSUE THREAD

**Issue by mthaddon** [canonical/httprequest-lego-k8s-operator#129]
#### Describe the bug

The charm doesn't react to pebble_ready so if the workload container restarts the charm stays in maintenance status.

#### To Reproduce

1. Deploy the charm
2. Restart the workload (lego) container
3. Observe the status in juju remains as "maintenance"

#### Expected behavior

The charm should be active/idle.

#### Screenshots

N/A

#### Logs

N/A

#### Environment

- Charm / library version (if relevant): 40
- Juju version (output from `juju --version`): 3.1.8
- Cloud Environment: OpenStack
- Kubernetes version (output from `kubectl version --short`): Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.26.15

#### Additional context

N/A

**Comment by gruyaume** [comment]
Thank you for opening this issue @mthaddon, we added this to our next pulse.

**Comment by mthaddon** [comment]
I can't see a way to manually kill the workload container for this charm, as there's no shell for me to connect to the workload container, and pebble plan seems to be empty (I've just deployed the charm and set `httpreq_endpoint` and `email` but not related it to anything). Do you have any ideas of how to manually kill the lego container so that I can test this?

**Comment by gruyaume** [comment]
Indeed, there is no pebble plan, we are only using LEGO cli calls when needed. Here I simply deleted the k8s pod. 

`kubectl delete pod <pod name> -n <model name>`

**Comment by mthaddon** [comment]
@gruyaume that deletes the entire pod. What I need to do here to confirm if the bug is fixed is to delete the lego container but leave the charm container running.

**Comment by mthaddon** [comment]
Just for a bit more context, here's the output of `kubectl describe pod` and the previous container logs for the lego container on an instance manifesting this bug: https://pastebin.ubuntu.com/p/nZdqgtKkwt/

As you can see, the lego container has been restarted twice, and the last restart was on `Wed, 17 Apr 2024 19:11:04 +0000`.

**Comment by gruyaume** [comment]
I'm quite confident this would have been fixed by switching to "collect status" as status will be evaluated at every event now.

**Comment by gruyaume** [comment]
Closing this as this was addressed by leveraging collect status. You can run `juju refresh` to get the latest charm version.
