### ISSUE TITLE
The default `expiry_notification_time` may be too short for typical ACME certificates

### ISSUE THREAD

**Issue by weiiwang01** [canonical/httprequest-lego-k8s-operator#96]
Currently, the default `expiry_notification_time` for `TLSCertificatesRequiresV3` is set to 7 days, which is longer than the recommended renewal interval of Let's Encrypt, suggesting a renewal of the certificate 30 days before expiration. https://letsencrypt.org/docs/faq/#what-is-the-lifetime-for-let-s-encrypt-certificates-for-how-long-are-they-valid

https://github.com/canonical/httprequest-lego-k8s-operator/blob/8329614e65ca972701b06abba288a87fad1f2076/lib/charms/tls_certificates_interface/v3/tls_certificates.py#L1457-L1467

**Comment by saltiyazan** [comment]
Hi @weiiwang01,

This a parameter on the requirer side of the lib, any requirer can set it when initialising the lib.
Do you see any reason to change the default value? Requirer charms implementing the lib won't be necessarily using Let's Encrypt certificates.

**Comment by weiiwang01** [comment]
> Hi @weiiwang01,
> 
> This a parameter on the requirer side of the lib, any requirer can set it when initialising `TLSCertificatesRequiresV3`. Do you see any reason to change the default value? Requirer charms implementing the lib won't be necessarily using Let's Encrypt certificates.

Yes, but the requirer charm cannot decide which certificate provider it will receive, as it doesn't know which provider charm is integrated. Does this mean that a dynamic value, calculated by examining the received certificates or set by the provider side, would be more appropriate?

**Comment by saltiyazan** [comment]
> > Hi @weiiwang01,
> > This a parameter on the requirer side of the lib, any requirer can set it when initialising `TLSCertificatesRequiresV3`. Do you see any reason to change the default value? Requirer charms implementing the lib won't be necessarily using Let's Encrypt certificates.
> 
> Yes, but the requirer charm cannot decide which certificate provider it will receive, as it doesn't know which provider charm is integrated. Does this mean that a dynamic value, calculated by examining the received certificates or set by the provider side, would be more appropriate?

I get your point now, I'm working on a fix.

**Comment by saltiyazan** [comment]
PR opened https://github.com/canonical/tls-certificates-interface/pull/147
